In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [2]:
df = pd.read_csv("1_boston_housing.csv")
df.shape

(506, 14)

In [3]:
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [4]:
df.tail(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
496,0.28960,0.0,9.69,0,0.585,5.390,72.9,2.7986,6,391,19.2,396.90,21.14,19.7
497,0.26838,0.0,9.69,0,0.585,5.794,70.6,2.8927,6,391,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0,0.585,6.019,65.3,2.4091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [5]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [7]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [8]:
df.corr()['MEDV'].sort_values()

LSTAT     -0.737663
PTRATIO   -0.507787
INDUS     -0.483725
TAX       -0.468536
NOX       -0.427321
CRIM      -0.388305
RAD       -0.381626
AGE       -0.376955
CHAS       0.175260
DIS        0.249929
B          0.333461
ZN         0.360445
RM         0.695360
MEDV       1.000000
Name: MEDV, dtype: float64

In [9]:
X = df.loc[:,['LSTAT','RM','PTRATIO']]
Y = df.loc[:,["MEDV"]]
X.shape, Y.shape

((506, 3), (506, 1))

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.25, random_state = 10)

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(x_train)

StandardScaler()

In [13]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
model = Sequential()

In [15]:
model.add(Dense(128, input_shape=(3,), activation='relu', name= 'input'))
model.add(Dense(64, activation='relu', name='layer_1'))
model.add(Dense(1, activation='linear', name='output'))
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\prath\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input (Dense)                        │ (None, 128)                 │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ output (Dense)                       │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,833 (34.50 KB)

 Trainable params: 8,833 (34.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.fit(x_train, y_train, epochs= 100, validation_split= 0.05)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 535.3019 - mae: 21.4927 - val_loss: 701.2382 - val_mae: 23.8413
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 498.3381 - mae: 20.6841 - val_loss: 657.1893 - val_mae: 22.9357
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 449.9504 - mae: 19.6047 - val_loss: 597.5295 - val_mae: 21.6568
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 386.8823 - mae: 18.0747 - val_loss: 518.1585 - val_mae: 19.8486
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 304.5949 - mae: 15.9124 - val_loss: 422.2592 - val_mae: 17.6194
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 214.2919 - mae: 13.2633 - val_loss: 320.0487 - val_mae: 14.9509
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 127.2508 - mae: 10.1541 - val_loss: 228.8127 - val_mae: 11.9457
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.8642 - mae: 7.2210 - val_loss: 164.3224 - val_mae: 9.1897
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 46.1046 - mae: 5.4275 - val_loss: 129.1994 - val_mae: 7.7147
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 39.1730 - mae: 4.8604 - val_loss: 114.3118 - val_mae: 7.2474
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 34.2513 - mae: 4.4251 - val_loss: 105.1324 - val_mae: 7.0467
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.3754 - mae: 4.0897 - val_loss: 101.7755 - val_mae: 6.9823
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.6857 - mae: 3.8905 - val_loss: 96.5538 - val_mae: 6.8152
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.7523 - mae: 3.7509 - val_loss: 93.7645 - val_mae: 6.7381
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.5586 - mae: 3.6650 - val_loss: 90.8890 - val_mae: 6.6827
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.5571 - mae: 3.5842 - val_loss: 88.9352 - val_mae: 6.6184
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.6848 - mae: 3.4963 - val_loss: 88.5196 - val_mae: 6.5819
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.0510 - mae: 3.4441 - val_loss: 88.4374 - val_mae: 6.5624
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.3839 - mae: 3.3949 - val_loss: 87.4682 - val_mae: 6.5146
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.9697 - mae: 3.3695 - val_loss: 86.8845 - val_mae: 6.4788
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.4526 - mae: 3.3338 - val_loss: 85.7644 - val_mae: 6.4200
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.0175 - mae: 3.2970 - val_loss: 85.4757 - val_mae: 6.4001
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.6600 - mae: 3.2633 - val_loss: 85.4542 - val_mae: 6.3870
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.3914 - mae: 3.2319 - val_loss: 86.1337 - val_mae: 6.3557
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18.9750 - mae: 3.2069 - val_loss: 84.1970 - val_mae: 6.2636
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.5801 - mae: 3.1711 - val_loss: 83.2393 - val_mae: 6.2164
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18.3605 - mae: 3.1571 - val_loss: 83.6095 - val_mae: 6.1728
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.0294 - mae: 3.1274 - val_loss: 83.0223 - val_mae: 6.1921
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17.7407 - mae: 3.1052 - val_loss: 82.1780 - val_mae: 6.0871
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.4518 - mae: 3.0803 - val_loss: 82.3169 - val_mae: 6.0655
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17.2383 - mae: 3.0535 - val_loss: 82.0830 - val_mae: 6.0180
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.9914 - mae: 3.0213 - val_loss: 83.0960 - val_mae: 6.0098
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.8325 - mae: 3.0068 - val_loss: 84.5110 - val_mae: 6.0311
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.5112 - mae: 2.9678 - val_loss: 82.5983 - val_mae: 5.9402
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.4444 - mae: 2.9638 - val_loss: 80.7747 - val_mae: 5.8604
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.1484 - mae: 2.9465 - val_loss: 85.5827 - val_mae: 6.0265
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.1435 - mae: 2.9522 - val_loss: 84.0556 - val_mae: 5.9291
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.8513 - mae: 2.9265 - val_loss: 82.9659 - val_mae: 5.8801
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.7413 - mae: 2.9063 - val_loss: 81.5909 - val_mae: 5.7837
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.5471 - mae: 2.8871 - val_loss: 81.7798 - val_mae: 5.7784
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.4349 - mae: 2.8651 - val_loss: 80.7564 - val_mae: 5.7378
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.1738 - mae: 2.8427 - val_loss: 80.6258 - val_mae: 5.7051
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.0767 - mae: 2.8270 - val_loss: 80.2909 - val_mae: 5.6671
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.9403 - mae: 2.8228 - val_loss: 81.2100 - val_mae: 5.6975
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.7785 - mae: 2.7997 - val_loss: 80.9962 - val_mae: 5.6782
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.6787 - mae: 2.7858 - val_loss: 80.2512 - val_mae: 5.6308
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.4413 - mae: 2.7720 - val_loss: 80.3966 - val_mae: 5.6319
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.3181 - mae: 2.7706 - val_loss: 80.6772 - val_mae: 5.6103
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.1504 - mae: 2.7387 - val_loss: 80.9389 - val_mae: 5.5912
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.0600 - mae: 2.7261 - val_loss: 79.8928 - val_mae: 5.5399
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.9248 - mae: 2.7064 - val_loss: 79.3204 - val_mae: 5.4716
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.7584 - mae: 2.6824 - val_loss: 79.4930 - val_mae: 5.4638
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.6101 - mae: 2.6710 - val_loss: 79.5505 - val_mae: 5.4569
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.5078 - mae: 2.6709 - val_loss: 79.8961 - val_mae: 5.4697
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.3705 - mae: 2.6546 - val_loss: 79.5733 - val_mae: 5.4489
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.2546 - mae: 2.6397 - val_loss: 79.8300 - val_mae: 5.4339
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.1181 - mae: 2.6232 - val_loss: 80.4553 - val_mae: 5.4293
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.1306 - mae: 2.6372 - val_loss: 79.1723 - val_mae: 5.3651
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7643 - mae: 2.5872 - val_loss: 82.0323 - val_mae: 5.3885
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.9286 - mae: 2.5856 - val_loss: 82.2611 - val_mae: 5.3653
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.8966 - mae: 2.6079 - val_loss: 84.2846 - val_mae: 5.4519
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5594 - mae: 2.5886 - val_loss: 80.0152 - val_mae: 5.3602
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.4749 - mae: 2.5674 - val_loss: 78.5812 - val_mae: 5.2823
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.3107 - mae: 2.5447 - val_loss: 80.1254 - val_mae: 5.2935
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.2311 - mae: 2.5482 - val_loss: 79.6527 - val_mae: 5.2388
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.2092 - mae: 2.5294 - val_loss: 79.5262 - val_mae: 5.2124
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.9268 - mae: 2.5074 - val_loss: 79.9209 - val_mae: 5.1989
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.8472 - mae: 2.5010 - val_loss: 79.6515 - val_mae: 5.1674
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.8147 - mae: 2.4835 - val_loss: 79.6413 - val_mae: 5.1680
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.7248 - mae: 2.4855 - val_loss: 79.3821 - val_mae: 5.1837
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.5667 - mae: 2.4670 - val_loss: 79.4896 - val_mae: 5.1450
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.5188 - mae: 2.4615 - val_loss: 80.0114 - val_mae: 5.1460
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.4431 - mae: 2.4504 - val_loss: 79.4502 - val_mae: 5.1607
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.3716 - mae: 2.4467 - val_loss: 81.0369 - val_mae: 5.1605
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4235 - mae: 2.4382 - val_loss: 79.6061 - val_mae: 5.1168
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.1930 - mae: 2.4212 - val_loss: 82.0717 - val_mae: 5.2418
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2211 - mae: 2.4464 - val_loss: 80.4239 - val_mae: 5.1637
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1265 - mae: 2.4211 - val_loss: 80.8001 - val_mae: 5.1613
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.0120 - mae: 2.4186 - val_loss: 83.7530 - val_mae: 5.2190
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.9850 - mae: 2.4141 - val_loss: 82.1086 - val_mae: 5.1417
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.1063 - mae: 2.4311 - val_loss: 81.2463 - val_mae: 5.1125
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.0781 - mae: 2.4306 - val_loss: 83.0151 - val_mae: 5.2433
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.6924 - mae: 2.3802 - val_loss: 79.4646 - val_mae: 5.0400
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.8065 - mae: 2.3817 - val_loss: 81.6550 - val_mae: 5.1106
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.6902 - mae: 2.3645 - val_loss: 81.8085 - val_mae: 5.1838
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5928 - mae: 2.3695 - val_loss: 80.9279 - val_mae: 5.1306
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5810 - mae: 2.3639 - val_loss: 81.5239 - val_mae: 5.1689
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5446 - mae: 2.3513 - val_loss: 80.6179 - val_mae: 5.0986
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.4805 - mae: 2.3483 - val_loss: 82.6378 - val_mae: 5.1176
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5163 - mae: 2.3512 - val_loss: 82.5751 - val_mae: 5.1114
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.6227 - mae: 2.3656 - val_loss: 81.6603 - val_mae: 5.0704
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.6094 - mae: 2.3697 - val_loss: 84.0435 - val_mae: 5.1378
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.3298 - mae: 2.3261 - val_loss: 80.7838 - val_mae: 5.0613
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3297 - mae: 2.3341 - val_loss: 82.3857 - val_mae: 5.0835
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2887 - mae: 2.3233 - val_loss: 83.6660 - val_mae: 5.1290
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1974 - mae: 2.3069 - val_loss: 80.0298 - val_mae: 5.0346
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.2802 - mae: 2.3230 - val_loss: 81.3818 - val_mae: 5.0476
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2513 - mae: 2.3198 - val_loss: 83.5890 - val_mae: 5.1119
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1023 - mae: 2.3046 - val_loss: 82.8366 - val_mae: 5.0906
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.0496 - mae: 2.3060 - val_loss: 82.0774 - val_mae: 5.0729

In [17]:
output = model.evaluate(x_test,y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.1534 - mae: 3.1759

In [18]:
print(f"Mean Squared Error: {output[0]}"
     ,f"Mean Absolute Error: {output[1]}", sep="\n")

Mean Squared Error: 23.153364181518555
Mean Absolute Error: 3.1758873462677

In [19]:
y_pred = model.predict(x_test).flatten()
y_test = y_test.values.flatten()

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

In [20]:
for i in range(5):
    print(f"Actual: {y_test[i]:.2f} | Predicted: {y_pred[i]:.2f}")

Actual: 28.40 | Predicted: 25.47
Actual: 31.10 | Predicted: 30.72
Actual: 23.50 | Predicted: 25.49
Actual: 26.60 | Predicted: 27.21
Actual: 19.60 | Predicted: 18.41

In [21]:
# import matplotlib.pyplot as plt
# plt.plot(history.history['loss'], label='Training Loss')
# plt.plot(history.history['val_loss'], label='Validation Loss')
# plt.legend()
# plt.title("Loss Graph")
# plt.xlabel("Epoch")
# plt.ylabel("Loss")
# plt.show()

In [22]:
print(*zip(y_pred,y_test))

(np.float32(25.465908), np.float64(28.4)) (np.float32(30.718863), np.float64(31.1)) (np.float32(25.486952), np.float64(23.5)) (np.float32(27.207909), np.float64(26.6)) (np.float32(18.40655), np.float64(19.6)) (np.float32(16.726606), np.float64(14.3)) (np.float32(42.28729), np.float64(50.0)) (np.float32(14.730826), np.float64(14.3)) (np.float32(20.17052), np.float64(20.7)) (np.float32(43.44113), np.float64(37.6)) (np.float32(18.012869), np.float64(20.4)) (np.float32(27.488379), np.float64(27.5)) (np.float32(22.81267), np.float64(36.2)) (np.float32(32.245613), np.float64(32.0)) (np.float32(31.089909), np.float64(33.1)) (np.float32(53.208416), np.float64(48.8)) (np.float32(25.89115), np.float64(24.6)) (np.float32(18.988152), np.float64(26.4)) (np.float32(20.96483), np.float64(23.2)) (np.float32(19.519724), np.float64(17.0)) (np.float32(33.176643), np.float64(41.3)) (np.float32(15.759938), np.float64(14.9)) (np.float32(22.862057), np.float64(18.5)) (np.float32(25.12469), np.float64(25.0)) (np.float32(37.119648), np.float64(36.4)) (np.float32(20.966541), np.float64(19.5)) (np.float32(18.622458), np.float64(27.1)) (np.float32(16.851315), np.float64(14.9)) (np.float32(43.442055), np.float64(46.0)) (np.float32(11.118379), np.float64(17.9)) (np.float32(34.639034), np.float64(30.3)) (np.float32(32.773933), np.float64(31.6)) (np.float32(26.691374), np.float64(23.1)) (np.float32(24.398226), np.float64(24.7)) (np.float32(15.21249), np.float64(16.7)) (np.float32(19.806227), np.float64(18.3)) (np.float32(8.72364), np.float64(8.4)) (np.float32(31.733877), np.float64(37.3)) (np.float32(25.002594), np.float64(22.1)) (np.float32(24.975357), np.float64(22.0)) (np.float32(39.396404), np.float64(46.7)) (np.float32(26.809643), np.float64(30.1)) (np.float32(13.963917), np.float64(12.1)) (np.float32(28.798363), np.float64(29.1)) (np.float32(18.026688), np.float64(16.6)) (np.float32(27.638245), np.float64(23.9)) (np.float32(18.027506), np.float64(19.9)) (np.float32(18.705858), np.float64(21.4)) (np.float32(45.336666), np.float64(45.4)) (np.float32(16.46491), np.float64(15.6)) (np.float32(19.685026), np.float64(22.7)) (np.float32(14.711165), np.float64(12.5)) (np.float32(20.535402), np.float64(24.3)) (np.float32(39.587513), np.float64(43.8)) (np.float32(23.520403), np.float64(22.0)) (np.float32(34.91412), np.float64(33.8)) (np.float32(19.229029), np.float64(19.3)) (np.float32(19.099394), np.float64(22.6)) (np.float32(21.356325), np.float64(16.1)) (np.float32(20.830948), np.float64(15.0)) (np.float32(18.701117), np.float64(19.6)) (np.float32(21.562662), np.float64(21.2)) (np.float32(53.07797), np.float64(50.0)) (np.float32(57.848717), np.float64(50.0)) (np.float32(27.456066), np.float64(29.4)) (np.float32(15.085671), np.float64(17.8)) (np.float32(25.013742), np.float64(22.8)) (np.float32(12.193392), np.float64(8.8)) (np.float32(27.53921), np.float64(32.5)) (np.float32(39.007984), np.float64(42.8)) (np.float32(16.79323), np.float64(12.6)) (np.float32(28.207396), np.float64(28.6)) (np.float32(17.809847), np.float64(19.1)) (np.float32(21.559742), np.float64(50.0)) (np.float32(20.86597), np.float64(27.5)) (np.float32(13.026941), np.float64(23.7)) (np.float32(47.89098), np.float64(50.0)) (np.float32(10.034065), np.float64(7.2)) (np.float32(19.867105), np.float64(18.7)) (np.float32(32.70712), np.float64(37.0)) (np.float32(19.679838), np.float64(22.9)) (np.float32(25.23829), np.float64(22.9)) (np.float32(19.2246), np.float64(17.1)) (np.float32(24.850561), np.float64(22.0)) (np.float32(31.614689), np.float64(23.6)) (np.float32(24.842432), np.float64(23.9)) (np.float32(25.862932), np.float64(27.1)) (np.float32(34.284958), np.float64(29.0)) (np.float32(24.200468), np.float64(22.2)) (np.float32(10.983198), np.float64(7.0)) (np.float32(23.382809), np.float64(20.7)) (np.float32(20.748686), np.float64(18.5)) (np.float32(24.500532), np.float64(21.6)) (np.float32(24.801094), np.float64(23.0)) (np.float32(18.96372), np.float64(16.0)) (np.float32(19.454842), np.float64(15.0)) (np.float32(25.951185), np.float64(23.9)) (np.float32(19.963194), np.float64(24.4)) (np.float32(20.637655), np.float64(22.6)) (np.float32(18.62798), np.float64(19.8)) (np.float32(22.060644), np.float64(22.2)) (np.float32(19.620552), np.float64(18.6)) (np.float32(19.379297), np.float64(19.7)) (np.float32(23.677328), np.float64(23.1)) (np.float32(13.579321), np.float64(13.5)) (np.float32(21.717205), np.float64(21.2)) (np.float32(18.144644), np.float64(23.1)) (np.float32(15.410107), np.float64(13.6)) (np.float32(28.58154), np.float64(22.8)) (np.float32(23.38286), np.float64(18.2)) (np.float32(11.540035), np.float64(13.1)) (np.float32(17.857244), np.float64(23.2)) (np.float32(25.537115), np.float64(22.8)) (np.float32(25.510187), np.float64(25.1)) (np.float32(22.061571), np.float64(18.9)) (np.float32(13.717287), np.float64(10.9)) (np.float32(15.156017), np.float64(19.3)) (np.float32(20.35214), np.float64(17.4)) (np.float32(17.986643), np.float64(15.6)) (np.float32(20.001196), np.float64(20.6)) (np.float32(28.984545), np.float64(50.0)) (np.float32(35.98041), np.float64(32.7)) (np.float32(20.85037), np.float64(21.8)) (np.float32(16.735937), np.float64(13.4)) (np.float32(17.631334), np.float64(16.6)) (np.float32(23.797377), np.float64(23.6)) (np.float32(12.668961), np.float64(11.0))